
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{title}}</title>
    </head>
    <body>
        <div>
<div id="ux-header">
    <h1>{{title}}</h1>
</div>
<div id="Content">
    {{content}}
</div>
<div id="ux-footer">
    Footer
</div>
<!-- Visual Studio Browser Link -->
<script type="application/json" id="__browserLink_initializationData">
    {"requestId":"2b41e14c454c437f83294011ac09a1a4","requestMappingFromServer":false}
</script>
<script type="text/javascript" src="http://localhost:46256/96c263055b5341fc8fadfd4607fce1e2/browserLink" async="async"></script>
<!-- End Browser Link -->

</body>
</html>
