<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title}}</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="new/newschema/openpublish/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="new/newschema/openpublish/css/freelancer.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="new/newschema/openpublish/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">{{title}}</a>
            </div>
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-text">
                        <span class="name">{{title}}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Content</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                {{content}}
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; MSDN China 2015
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="new/newschema/openpublish/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="new/newschema/openpublish/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="new/newschema/openpublish/js/classie.js"></script>
    <script src="new/newschema/openpublish/js/cbpAnimatedHeader.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="new/newschema/openpublish/js/jqBootstrapValidation.js"></script>
    <script src="new/newschema/openpublish/js/contact_me.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="new/newschema/openpublish/js/freelancer.js"></script>

</body>

</html>
